version: '3.4'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: CleanArchitectureDB
      POSTGRES_PASSWORD: Password1!
      POSTGRES_PORT: 5432
      POSTGRES_USER: CleanArchitectureDB
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/Apps/CleanArchitecture.Api/Dockerfile
    ports:
      - "5006:443"
      - "5005:80"
    environment:
      UseInMemoryDatabase: "false"
      ConnectionStrings__DefaultConnection_Postgres: "User ID=CleanArchitectureDB;Password=Password1!;Server=postgres-db;Port=5432;Database=CleanArchitectureDB;Integrated Security=true;Pooling=true;"
      IdentityServer__Key__Type: "Development"
    restart: on-failure
    depends_on:
      - postgres-db
   
volumes:
  pgdata:
